// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Проверить жизнеспособность сервиса",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health.DtoIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/upload": {
            "post": {
                "description": "Uploads a PDF document and processes it",
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a PDF document",
                "parameters": [
                    {
                        "type": "file",
                        "description": "PDF file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/upload.DtoOut"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.DtoIn": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "upload.DtoOut": {
            "type": "object",
            "properties": {
                "document_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
